// flow-typed signature: a69f4801d27e8c65d980f0986e133a22
// flow-typed version: <<STUB>>/prettier-standard_v^1.0.6/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-standard/lib/format-files' {
  declare module.exports: any;
}

declare module 'prettier-standard/lib/format-files.test' {
  declare module.exports: any;
}

declare module 'prettier-standard/lib/index' {
  declare module.exports: any;
}

declare module 'prettier-standard/lib/message.test' {
  declare module.exports: any;
}

declare module 'prettier-standard/lib/messages' {
  declare module.exports: any;
}

declare module 'prettier-standard/lib/no-main' {
  declare module.exports: any;
}

declare module 'prettier-standard/src/format-files' {
  declare module.exports: any;
}

declare module 'prettier-standard/src/format-files.test' {
  declare module.exports: any;
}

declare module 'prettier-standard/src/index' {
  declare module.exports: any;
}

declare module 'prettier-standard/src/message.test' {
  declare module.exports: any;
}

declare module 'prettier-standard/src/messages' {
  declare module.exports: any;
}

declare module 'prettier-standard/src/no-main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-standard/lib/format-files.js' {
  declare module.exports: $Exports<'prettier-standard/lib/format-files'>;
}
declare module 'prettier-standard/lib/format-files.test.js' {
  declare module.exports: $Exports<'prettier-standard/lib/format-files.test'>;
}
declare module 'prettier-standard/lib/index.js' {
  declare module.exports: $Exports<'prettier-standard/lib/index'>;
}
declare module 'prettier-standard/lib/message.test.js' {
  declare module.exports: $Exports<'prettier-standard/lib/message.test'>;
}
declare module 'prettier-standard/lib/messages.js' {
  declare module.exports: $Exports<'prettier-standard/lib/messages'>;
}
declare module 'prettier-standard/lib/no-main.js' {
  declare module.exports: $Exports<'prettier-standard/lib/no-main'>;
}
declare module 'prettier-standard/src/format-files.js' {
  declare module.exports: $Exports<'prettier-standard/src/format-files'>;
}
declare module 'prettier-standard/src/format-files.test.js' {
  declare module.exports: $Exports<'prettier-standard/src/format-files.test'>;
}
declare module 'prettier-standard/src/index.js' {
  declare module.exports: $Exports<'prettier-standard/src/index'>;
}
declare module 'prettier-standard/src/message.test.js' {
  declare module.exports: $Exports<'prettier-standard/src/message.test'>;
}
declare module 'prettier-standard/src/messages.js' {
  declare module.exports: $Exports<'prettier-standard/src/messages'>;
}
declare module 'prettier-standard/src/no-main.js' {
  declare module.exports: $Exports<'prettier-standard/src/no-main'>;
}
